version: "3"

services:
  frontend:
    env_file:
      - ./frontend/.env
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  backend:
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend/:/code/
    ports:
      - 5050:5050