version: "3.8"

services:
  redis:
    image: redis:latest@sha256:a7cee7c8178ff9b5297cb109e6240f5072cdaaafd775ce6b586c3c704b06458e
    container_name: redis
    restart: always
    ports:
      - 6379:6379
