blank_issues_enabled: false
contact_links:
  - name: Quivr Community Discord
    url: https://discord.gg/HUpRgp2HG8
    about: Please ask and answer questions here.
  - name: Twitter
    url: https://twitter.com/Quivr_brain
    about: Follow us on Twitter for updates.
